resolver: lts-7.2
packages:
- '.'
- location:
    git: https://github.com/lpeterse/haskell-socket.git
    commit: 4259948e20dac97d2341a264e5c9c7b66b986b3f
extra-deps: []
flags: {}
extra-package-dbs: []
