resolver: lts-7.10
packages:
  - '.'
  - location:
      git: https://github.com/lpeterse/haskell-socket.git
      commit: 142561b7daacc35d1e8ddce22363bea73b8c281e
extra-deps:
  - socket-0.8.0.0
flags: {}
extra-package-dbs: []
